cat("========================================\n")
cat("百度对比测试\n")
cat("========================================\n\n")

library(chromote)

cat("测试 1: 访问百度\n")
b1 <- ChromoteSession$new()
b1$go_to("https://www.baidu.com")
Sys.sleep(3)
b1$screenshot("baidu_test.png")
result <- b1$Runtime$evaluate("document.title")
cat(paste("  标题: ", result$value, "\n", sep = ""))
b1$close()
cat("  ✓ 完成\n")

cat("\n测试 2: 访问管理系统\n")
b2 <- ChromoteSession$new()
b2$go_to("https://fac2023.lbbtech.com/?canaryflag=1#/home/index")
Sys.sleep(3)
b2$screenshot("system_test.png")
result <- b2$Runtime$evaluate("document.title")
cat(paste("  标题: ", result$value, "\n", sep = ""))
b2$close()
cat("  ✓ 完成\n")

cat("\n========================================\n")
cat("对比完成\n")
cat("========================================\n")